(()=>{
'use strict';
const API='https://dhnrrruishllmnhafjdd.supabase.co/functions/v1/ges-quiz-api';
const $=id=>document.getElementById(id);
const state={token:'',deviceId:'',user:null,settings:{},bank:window.FREE_BANK||[],attempt:null,quiz:[],answers:{},index:0,startedAt:0,timer:null,left:0};
try{state.token=localStorage.getItem('promo_token_v4')||localStorage.getItem('promo_token_v3')||''}catch{}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(msg,bad=false){const x=$('toastRoot');if(!x)return;x.innerHTML=`<div class="toast ${bad?'bad':''}">${esc(msg)}</div>`;setTimeout(()=>{if(x)x.innerHTML=''},3500)}
function setView(id){['authScreen','dashboardScreen','quizScreen','resultScreen','performanceScreen'].forEach(x=>$(x)?.classList.add('hidden'));$(id)?.classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})}
function showAuth(mode='chooser'){
 setView('authScreen');
 $('authChooser')?.classList.toggle('hidden',mode!=='chooser');
 $('registerPanel')?.classList.toggle('hidden',mode!=='register');
 $('loginPanel')?.classList.toggle('hidden',mode!=='login');
 if($('authTitle'))$('authTitle').textContent=mode==='register'?'Create your account':mode==='login'?'Welcome back':'Choose how to continue';
 if($('authSubtitle'))$('authSubtitle').textContent=mode==='register'?'First time here? Register once, then begin the free 30-question practice.':mode==='login'?'Already registered? Enter the same telephone number and 4-digit password.':'New users register first. Existing users log in and go straight to their practice dashboard.';
 setTimeout(()=>{(mode==='login'?$('loginPhone'):mode==='register'?$('regName'):null)?.focus({preventScroll:true})},80);
}
function randomDeviceId(){try{const a=new Uint8Array(16);crypto.getRandomValues(a);return 'dev_'+Array.from(a,b=>b.toString(16).padStart(2,'0')).join('')}catch{return 'dev_'+Date.now()+'_'+Math.random().toString(36).slice(2)}}
function storageRead(){try{return localStorage.getItem('promo_device_v4')||localStorage.getItem('promo_device_v3')||''}catch{return ''}}
function setupDeviceInBackground(){
 let id=storageRead()||randomDeviceId();state.deviceId=id;
 try{localStorage.setItem('promo_device_v4',id)}catch{}
 try{document.cookie=`promo_device_v4=${encodeURIComponent(id)}; Max-Age=157680000; Path=/; SameSite=Lax; Secure`}catch{}
 if(!('indexedDB' in window))return;
 try{const r=indexedDB.open('promo_secure_store_v4',1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('kv'))r.result.createObjectStore('kv')};r.onsuccess=()=>{try{const tx=r.result.transaction('kv','readwrite');tx.objectStore('kv').put(id,'deviceId')}catch{}}}catch{}
}
async function api(action,body={}){
 const c=new AbortController(),t=setTimeout(()=>c.abort(),12000);
 try{
  const payload={action,...body};if(['register','login'].includes(action))payload.deviceId=state.deviceId||storageRead()||randomDeviceId();
  const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json',...(state.token?{Authorization:'Bearer '+state.token}:{})},body:JSON.stringify(payload),signal:c.signal});
  const d=await r.json().catch(()=>({error:'The server returned an unreadable response.'}));
  if(!r.ok)throw Object.assign(new Error(d.error||'Request failed'),{data:d,status:r.status});return d;
 }catch(e){if(e?.name==='AbortError')throw new Error('The connection took too long. Check your internet and try again.');throw e}finally{clearTimeout(t)}
}
function saveSession(d){state.token=d.token||'';state.user=d.user||null;state.settings=d.settings||{};try{localStorage.setItem('promo_token_v4',state.token);localStorage.removeItem('promo_token_v3')}catch{}}
function clearSession(){state.token='';state.user=null;try{localStorage.removeItem('promo_token_v4');localStorage.removeItem('promo_token_v3')}catch{}}
function bindImmediate(){
 $('newUserCard')?.addEventListener('click',()=>showAuth('register'));
 $('existingUserCard')?.addEventListener('click',()=>showAuth('login'));
 document.querySelectorAll('[data-back-auth]').forEach(b=>b.addEventListener('click',()=>showAuth('chooser')));
 $('registerForm')?.addEventListener('submit',register);
 $('loginForm')?.addEventListener('submit',login);
 $('prevBtn')?.addEventListener('click',()=>{if(state.index>0){state.index--;renderQuestion()}});
 $('nextBtn')?.addEventListener('click',()=>{if(state.index<state.quiz.length-1){state.index++;renderQuestion()}else finishQuiz(false)});
 $('exitQuiz')?.addEventListener('click',()=>{if(confirm('Leave this practice? Your current answers will not be submitted.')){clearInterval(state.timer);renderDashboard()}});
}
async function register(e){e.preventDefault();const b=$('registerBtn');if(!b)return;b.disabled=true;b.textContent='Creating account…';try{const d=await api('register',{fullName:$('regName').value.trim(),phone:$('regPhone').value.trim(),pin:$('regPin').value});saveSession(d);toast('Registration successful. Your free practice is ready.');renderDashboard()}catch(err){toast(err.message||'Registration failed.',true)}finally{b.disabled=false;b.textContent='Register & Continue'}}
async function login(e){e.preventDefault();const b=$('loginBtn');if(!b)return;b.disabled=true;b.textContent='Checking account…';try{const d=await api('login',{phone:$('loginPhone').value.trim(),pin:$('loginPin').value});saveSession(d);toast('Login successful');await prepareBank();renderDashboard()}catch(err){toast(err.message||'Login failed.',true)}finally{b.disabled=false;b.textContent='Log In & Open Quiz'}}
async function restoreSession(){if(!state.token)return showAuth('chooser');try{const d=await api('me');state.user=d.user;state.settings=d.settings||{};await prepareBank();renderDashboard()}catch{clearSession();showAuth('chooser')}}
function b64Bytes(s){return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
async function prepareBank(){state.bank=window.FREE_BANK||[];if(state.user?.status!=='approved')return;if(!window.PREMIUM_BANK_DATA||!window.PREMIUM_BANK_IV)return toast('Full question bank is still loading. Reload once.',true);try{const k=await api('get_full_key');const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(k.key));const key=await crypto.subtle.importKey('raw',digest,{name:'AES-GCM'},false,['decrypt']);const compressed=await crypto.subtle.decrypt({name:'AES-GCM',iv:b64Bytes(window.PREMIUM_BANK_IV)},key,b64Bytes(window.PREMIUM_BANK_DATA));if(!('DecompressionStream' in window))throw new Error('Please update your browser for full-access question loading.');const stream=new Blob([compressed]).stream().pipeThrough(new DecompressionStream('gzip'));const bank=JSON.parse(await new Response(stream).text());if(!Array.isArray(bank)||bank.length<900)throw new Error('Question bank verification failed');state.bank=bank}catch(e){console.error(e);state.bank=window.FREE_BANK||[];toast(e.message||'Full question bank could not be opened.',true)}}
function historyKey(){return 'promo_hist_v4_'+(state.user?.id||'guest')}
function readHistory(){try{return JSON.parse(localStorage.getItem(historyKey())||'[]')}catch{return []}}
function addHistory(row){try{const h=readHistory();h.push(row);localStorage.setItem(historyKey(),JSON.stringify(h.slice(-50)))}catch{}}
function subTeaser(pending=false,completed=false){return `<section class="subscribe-card blink-border"><div class="sub-badge">✨ ${completed?'FREE PRACTICE COMPLETED':'FULL ACCESS AVAILABLE'}</div><h3>${completed?'Ready for more practice?':'Upgrade whenever you are ready'}</h3><p>${completed?'You can repeat the free 30-question practice, or activate full access for the complete question bank, flexible practice sizes and extended tools.':'Continue with the free 30-question practice. Full access unlocks the complete question bank, flexible practice sizes and extended performance tools.'}</p><div class="price">GH₵30</div><div class="momo"><small>MTN MOBILE MONEY</small><strong>0248 481 762</strong><b>ISAAC BOAHEN</b><button id="copyMomo" type="button" class="ghost">📋 Copy MoMo Number</button></div><a class="whatsapp" target="_blank" rel="noopener" href="https://wa.me/233248481762?text=${encodeURIComponent('Hello Sir Isaac, I want full access to the Promotion Exam Preparation Practice platform. I will pay/have paid GH₵30 to 0248 481 762, ISAAC BOAHEN. Please activate my account.')}">🟢 WhatsApp Sir Isaac</a><button id="subscribeBtn" type="button" class="primary block">${pending?'Activation Request Sent':'I Have Paid / Request Activation'}</button>${pending?'<small class="pending-text">Your activation request has been recorded. You can still repeat the free 30-question practice while waiting.</small>':''}</section>`}
function renderDashboard(){
 setView('dashboardScreen');const u=state.user||{},premium=u.status==='approved',pending=u.status==='pending',topics=[...new Set(state.bank.map(q=>q.topic).filter(Boolean))].sort(),ranks=[...new Set(state.bank.map(q=>q.rank).filter(Boolean))].sort();
 $('dashboardScreen').innerHTML=`<div class="dash-head"><div><small>WELCOME</small><h2>${esc(u.fullName||u.full_name||'Learner')}</h2><p>${premium?'Full access is active.':'Your free 30-question practice is ready.'}</p></div><button id="logoutBtn" type="button" class="ghost">Log out</button></div><div class="status-pill ${premium?'ok':pending?'pending':'free'}">${premium?'✓ FULL ACCESS':pending?'⏳ ACTIVATION REQUESTED':'FREE PRACTICE'}</div><section class="practice-card"><div class="card-icon">📝</div><div><h3>${premium?'Choose your practice':'Free 30-question practice'}</h3><p>${premium?'Choose a practice size and optional filters from the full question bank.':'Practise the free 30 questions, see your score, and repeat them as often as you need.'}</p></div>${premium?`<div class="grid2"><label>Questions<select id="countSel"><option>20</option><option selected>30</option><option>50</option><option>100</option><option>200</option></select></label><label>Rank<select id="rankSel"><option>All</option>${ranks.map(x=>`<option>${esc(x)}</option>`).join('')}</select></label></div><label>Topic<select id="topicSel"><option>All</option>${topics.map(x=>`<option>${esc(x)}</option>`).join('')}</select></label>`:''}<button id="startPractice" type="button" class="primary block pulse-soft">▶ ${premium?'Start Practice':'Start Free 30 Questions'}</button></section><div class="dash-actions"><button id="performanceBtn" type="button" class="action-card"><span>📈</span><b>My Performance</b><small>Scores and improvement</small></button></div>${premium?'':subTeaser(pending,false)}<div class="independent-note">Independent study and revision platform. Not an official Ghana Education Service examination portal.</div>`;
 $('logoutBtn').onclick=logout;$('startPractice').onclick=startPractice;$('performanceBtn').onclick=showPerformance;$('subscribeBtn')?.addEventListener('click',requestSubscription);$('copyMomo')?.addEventListener('click',copyMomo);
}
async function copyMomo(){try{await navigator.clipboard.writeText('0248481762');toast('MoMo number copied')}catch{toast('MoMo: 0248 481 762')}}
async function requestSubscription(){if(state.user?.status==='approved')return;try{const d=await api('request_subscription');state.user.status=d.status||'pending';toast('Activation request sent');renderDashboard()}catch(e){toast(e.message,true)}}
async function logout(){try{await api('logout')}catch{}clearSession();showAuth('chooser')}
async function startPractice(){const premium=state.user?.status==='approved';let count=premium?Number($('countSel')?.value||30):30,rank=premium?$('rankSel')?.value||'All':'All',topic=premium?$('topicSel')?.value||'All':'All';let pool=state.bank.filter(q=>(rank==='All'||q.rank===rank)&&(topic==='All'||q.topic===topic));if(!pool.length)return toast('No questions match those filters.',true);count=Math.min(count,pool.length);pool=[...pool].sort(()=>Math.random()-.5);state.quiz=pool.slice(0,count);state.answers={};state.index=0;state.startedAt=Date.now();try{state.attempt=await api('start_attempt',{count,rank,topic})}catch(e){return toast(e.message||'Could not start practice.',true)}state.left=count*60;setView('quizScreen');startTimer();renderQuestion()}
function startTimer(){clearInterval(state.timer);tick();state.timer=setInterval(()=>{state.left--;tick();if(state.left<=0){clearInterval(state.timer);finishQuiz(true)}},1000)}
function tick(){const m=Math.floor(Math.max(0,state.left)/60),s=Math.max(0,state.left)%60;if($('timerText'))$('timerText').textContent=`${m}:${String(s).padStart(2,'0')}`}
function renderQuestion(){const q=state.quiz[state.index];if(!q)return;const picked=state.answers[q.id];$('qProgress').textContent=`Question ${state.index+1} of ${state.quiz.length}`;$('answeredCount').textContent=`${Object.keys(state.answers).length} answered`;$('progressBar').style.width=`${((state.index+1)/state.quiz.length)*100}%`;$('qTags').innerHTML=`${q.rank?`<span class="tag">${esc(q.rank)}</span>`:''}${q.topic?`<span class="tag">${esc(q.topic)}</span>`:''}`;$('qNo').textContent=`QUESTION ${state.index+1}`;$('qText').innerHTML=q.q||q.question||'';$('options').innerHTML=(q.options||[]).map((o,i)=>`<button class="option ${picked!==undefined?(i===q.answer?'correct':i===picked?'wrong':''):''}" data-i="${i}" ${picked!==undefined?'disabled':''}><span class="letter">${String.fromCharCode(65+i)}</span><span class="otxt">${o}</span><span class="mark">${picked!==undefined?(i===q.answer?'✓':i===picked?'✕':''):''}</span></button>`).join('');$('explanation').classList.toggle('hidden',picked===undefined);$('explanation').innerHTML=picked===undefined?'':`<strong>Explanation:</strong> ${q.explanation||'Correct answer: '+((q.options||[])[q.answer]||'')}`;document.querySelectorAll('#options .option').forEach(b=>b.onclick=()=>answer(q,Number(b.dataset.i)));$('prevBtn').disabled=state.index===0;$('nextBtn').textContent=state.index===state.quiz.length-1?'Submit Practice':'Next →'}
function answer(q,i){if(state.answers[q.id]!==undefined)return;state.answers[q.id]=i;renderQuestion()}
async function finishQuiz(timedOut){clearInterval(state.timer);const score=state.quiz.reduce((n,q)=>n+(state.answers[q.id]===q.answer?1:0),0),answered=Object.keys(state.answers).length,duration=Math.round((Date.now()-state.startedAt)/1000);let r={score,total:state.quiz.length,answered,percentage:Math.round(score*100/state.quiz.length)};try{r=await api('submit_attempt',{attemptId:state.attempt?.attemptId,score,answered,durationSeconds:duration,timedOut})}catch(e){toast('Result saved on this device; server confirmation failed.',true)}addHistory({date:new Date().toISOString(),score:r.score??score,total:r.total??state.quiz.length,percentage:r.percentage??Math.round(score*100/state.quiz.length)});renderResult(r,state.user?.status!=='approved')}
function renderResult(r,free=false){setView('resultScreen');const pct=r.percentage??0;$('resultScreen').innerHTML=`<section class="result-card"><div class="result-ring"><strong>${pct}%</strong><span>${r.score}/${r.total}</span></div><h2>${pct>=80?'Excellent work!':pct>=60?'Good progress!':'Keep practising!'}</h2><p>You answered ${r.answered??Object.keys(state.answers).length} questions. ${free?'You can repeat the free 30 questions or activate full access below.':''}</p><button id="againBtn" type="button" class="primary block">${free?'Practise Free 30 Again':'Start Another Practice'}</button><button id="perfBtn2" type="button" class="ghost block">View Performance</button><button id="dashBtn" type="button" class="ghost block">Back to Dashboard</button></section>${free?subTeaser(state.user?.status==='pending',true):''}`;$('againBtn').onclick=startPractice;$('perfBtn2').onclick=showPerformance;$('dashBtn').onclick=renderDashboard;$('subscribeBtn')?.addEventListener('click',requestSubscription);$('copyMomo')?.addEventListener('click',copyMomo)}
async function showPerformance(){const local=readHistory();setView('performanceScreen');let rows=local,summary=null;if(state.user?.status==='approved'){try{const d=await api('performance');if(Array.isArray(d.attempts))rows=d.attempts.map(x=>({date:x.completed_at,score:x.score,total:x.question_count,percentage:x.percentage}));summary=d.summary}catch{}}if(!summary&&rows.length){const p=rows.map(x=>Number(x.percentage)||0),first=p[0],latest=p[p.length-1];summary={attempts:rows.length,average:Math.round(p.reduce((a,b)=>a+b,0)/p.length),best:Math.max(...p),improvement:latest-first}}$('performanceScreen').innerHTML=`<section class="panel"><div class="panel-head"><button id="perfBack" type="button" class="back">←</button><div><h3>My Performance</h3><small>Your practice progress</small></div></div>${summary?`<div class="stats"><div><strong>${summary.attempts}</strong><span>Attempts</span></div><div><strong>${summary.average}%</strong><span>Average</span></div><div><strong>${summary.best}%</strong><span>Best</span></div><div><strong>${summary.improvement>=0?'+':''}${summary.improvement}%</strong><span>Improvement</span></div></div>`:'<div class="hint">Complete a practice to start building your performance history.</div>'}<div class="history">${rows.slice().reverse().map((x,i)=>`<div class="history-row"><b>${x.percentage}%</b><span>${x.score}/${x.total}</span><small>${x.date?new Date(x.date).toLocaleString():`Attempt ${rows.length-i}`}</small></div>`).join('')}</div></section>`;$('perfBack').onclick=renderDashboard}
function boot(){bindImmediate();showAuth('chooser');setupDeviceInBackground();restoreSession()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();