(()=>{
'use strict';
const API='https://dhnrrruishllmnhafjdd.supabase.co/functions/v1/ges-quiz-api';
const $=id=>document.getElementById(id);
const state={token:localStorage.getItem('promo_token_v3')||'',user:null,settings:{},bank:window.FREE_BANK||[],attempt:null,quiz:[],answers:{},index:0,startedAt:0,timer:null,left:0};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(action,body={}){const c=new AbortController();const t=setTimeout(()=>c.abort(),15000);try{const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json',...(state.token?{Authorization:'Bearer '+state.token}:{})},body:JSON.stringify({action,...body}),signal:c.signal});const d=await r.json().catch(()=>({error:'Invalid server response'}));if(!r.ok)throw Object.assign(new Error(d.error||'Request failed'),{data:d,status:r.status});return d}finally{clearTimeout(t)}}
function toast(msg,bad=false){const x=$('toastRoot');x.innerHTML=`<div class="toast ${bad?'bad':''}">${esc(msg)}</div>`;setTimeout(()=>x.innerHTML='',2600)}
function setView(id){['authScreen','dashboardScreen','quizScreen','resultScreen','performanceScreen'].forEach(x=>$(x)?.classList.add('hidden'));$(id)?.classList.remove('hidden');scrollTo(0,0)}
function showAuth(mode='chooser'){setView('authScreen');$('authChooser').classList.toggle('hidden',mode!=='chooser');$('registerPanel').classList.toggle('hidden',mode!=='register');$('loginPanel').classList.toggle('hidden',mode!=='login');$('authTitle').textContent=mode==='register'?'Create your account':mode==='login'?'Welcome back':'Start your practice';$('authSubtitle').textContent=mode==='register'?'New users register once, then continue to the free practice.':mode==='login'?'Enter the same telephone number and 4-digit password you used when registering.':'Choose the option that applies to you.';}
async function boot(){bind();if(state.token){try{const d=await api('me');state.user=d.user;state.settings=d.settings||{};await prepareBank();renderDashboard();return}catch(e){localStorage.removeItem('promo_token_v3');state.token=''}}showAuth('chooser')}
function bind(){
 $('newUserCard').onclick=()=>showAuth('register');$('existingUserCard').onclick=()=>showAuth('login');document.querySelectorAll('[data-back-auth]').forEach(b=>b.onclick=()=>showAuth('chooser'));
 $('registerForm').onsubmit=async e=>{e.preventDefault();const b=$('registerBtn');b.disabled=true;b.textContent='Creating account…';try{const d=await api('register',{fullName:$('regName').value,phone:$('regPhone').value,pin:$('regPin').value});saveSession(d);toast('Registration successful');renderDashboard()}catch(err){toast(err.message,true)}finally{b.disabled=false;b.textContent='Register & Start Free Practice'}};
 $('loginForm').onsubmit=async e=>{e.preventDefault();const b=$('loginBtn');b.disabled=true;b.textContent='Logging in…';try{const d=await api('login',{phone:$('loginPhone').value,pin:$('loginPin').value});saveSession(d);await prepareBank();toast('Login successful');renderDashboard()}catch(err){toast(err.message,true)}finally{b.disabled=false;b.textContent='Log In & Open Quiz'}};
 $('prevBtn').onclick=()=>{if(state.index>0){state.index--;renderQuestion()}};$('nextBtn').onclick=()=>{if(state.index<state.quiz.length-1){state.index++;renderQuestion()}else finishQuiz(false)};$('exitQuiz').onclick=()=>{if(confirm('Leave this practice? Your current progress will not be submitted.')){clearInterval(state.timer);renderDashboard()}};
}
function saveSession(d){state.token=d.token;state.user=d.user;state.settings=d.settings||{};localStorage.setItem('promo_token_v3',state.token)}
async function prepareBank(){state.bank=window.FREE_BANK||[];if(state.user?.status==='approved'&&window.FULL_BANK_GZIP){try{const bytes=Uint8Array.from(atob(window.FULL_BANK_GZIP),c=>c.charCodeAt(0));const stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'));state.bank=JSON.parse(await new Response(stream).text())}catch(e){console.error(e);toast('Full question bank could not load on this browser. Please update Chrome.',true)}}}
function renderDashboard(){setView('dashboardScreen');const u=state.user||{};const premium=u.status==='approved';const pending=u.status==='pending';const topics=[...new Set(state.bank.map(q=>q.topic))].sort();const ranks=[...new Set(state.bank.map(q=>q.rank))].sort();$('dashboardScreen').innerHTML=`<div class="dash-head"><div><small>WELCOME</small><h2>${esc(u.fullName||u.full_name||'Learner')}</h2><p>${premium?'Full access active':'Free 30-question practice available'}</p></div><button id="logoutBtn" class="ghost">Log out</button></div>
<div class="status-pill ${premium?'ok':pending?'pending':'free'}">${premium?'✓ FULL ACCESS':'FREE PRACTICE'}</div>
<div class="practice-card"><div class="card-icon">📝</div><div><h3>${premium?'Choose your practice':'Free 30-question practice'}</h3><p>${premium?'Select the number of questions and optional filters.':'You can repeat the free 30 questions as many times as you want and monitor improvement.'}</p></div>
${premium?`<div class="grid2"><label>Questions<select id="countSel"><option>20</option><option selected>30</option><option>50</option><option>100</option><option>200</option></select></label><label>Rank<select id="rankSel"><option>All</option>${ranks.map(x=>`<option>${esc(x)}</option>`).join('')}</select></label></div><label>Topic<select id="topicSel"><option>All</option>${topics.map(x=>`<option>${esc(x)}</option>`).join('')}</select></label>`:''}<button id="startPractice" class="primary block pulse-soft">▶ Start Practice</button></div>
<div class="dash-actions"><button id="performanceBtn" class="action-card"><span>📈</span><b>My Performance</b><small>Scores & improvement</small></button></div>
${premium?'':subscriptionCard(pending)}<div class="independent-note">Independent study and revision platform. Not an official GES examination portal.</div>`;
$('logoutBtn').onclick=logout;$('startPractice').onclick=startPractice;$('performanceBtn').onclick=showPerformance;
$('subscribeBtn')?.addEventListener('click',requestSubscription);$('copyMomo')?.addEventListener('click',()=>navigator.clipboard?.writeText('0248481762').then(()=>toast('MoMo number copied')));
}
function subscriptionCard(pending){return `<section class="subscribe-card blink-border"><div class="spark">✨</div><div class="sub-badge">UNLOCK FULL ACCESS</div><h3>Continue beyond the free practice</h3><p>Access all 922 questions, flexible practice sizes, topic/rank filters, detailed performance and printable reports.</p><div class="price">GH₵30</div><div class="momo"><small>MTN MOBILE MONEY</small><strong>0248 481 762</strong><b>ISAAC BOAHEN</b><button id="copyMomo" class="ghost">Copy number</button></div><a class="whatsapp" target="_blank" rel="noopener" href="https://wa.me/233248481762?text=${encodeURIComponent('Hello Sir Isaac, I want full access to the Promotion Exam Preparation Practice platform. I have paid/will pay GH₵30 to 0248 481 762 (ISAAC BOAHEN). Please activate my account.')} ">🟢 WhatsApp Sir Isaac</a><button id="subscribeBtn" class="primary block">${pending?'Subscription Request Sent':'I Have Paid / Request Activation'}</button>${pending?'<small class="pending-text">Your request is awaiting approval.</small>':''}</section>`}
async function requestSubscription(){try{const d=await api('request_subscription');state.user.status=d.status||'pending';toast('Activation request sent');renderDashboard()}catch(e){toast(e.message,true)}}
async function startPractice(){const premium=state.user.status==='approved';let count=premium?Number($('countSel').value):30,rank=premium?$('rankSel').value:'All',topic=premium?$('topicSel').value:'All';let pool=state.bank.filter(q=>(rank==='All'||q.rank===rank)&&(topic==='All'||q.topic===topic));if(!pool.length)return toast('No questions match those filters.',true);count=Math.min(count,pool.length);pool=[...pool].sort(()=>Math.random()-.5);state.quiz=pool.slice(0,count);state.answers={};state.index=0;state.startedAt=Date.now();try{state.attempt=await api('start_attempt',{count,rank,topic});}catch(e){return toast(e.message,true)}state.left=count*60;setView('quizScreen');startTimer();renderQuestion()}
function startTimer(){clearInterval(state.timer);tick();state.timer=setInterval(()=>{state.left--;tick();if(state.left<=0){clearInterval(state.timer);finishQuiz(true)}},1000)}
function tick(){const m=Math.floor(state.left/60),s=state.left%60;$('timerText').textContent=`${m}:${String(s).padStart(2,'0')}`}
function renderQuestion(){const q=state.quiz[state.index],picked=state.answers[q.id];$('qProgress').textContent=`Question ${state.index+1} of ${state.quiz.length}`;$('answeredCount').textContent=`${Object.keys(state.answers).length} answered`;$('progressBar').style.width=`${((state.index+1)/state.quiz.length)*100}%`;$('qTags').innerHTML=`<span class="tag">${esc(q.rank)}</span><span class="tag">${esc(q.topic)}</span>`;$('qNo').textContent=`QUESTION ${state.index+1}`;$('qText').innerHTML=q.q;$('options').innerHTML=q.options.map((o,i)=>`<button class="option ${picked!==undefined?(i===q.answer?'correct':i===picked?'wrong':''):''}" data-i="${i}" ${picked!==undefined?'disabled':''}><span class="letter">${String.fromCharCode(65+i)}</span><span class="otxt">${o}</span><span class="mark">${picked!==undefined?(i===q.answer?'✓':i===picked?'✕':''):''}</span></button>`).join('');$('explanation').classList.toggle('hidden',picked===undefined);$('explanation').innerHTML=picked===undefined?'':`<strong>Explanation:</strong> ${q.explanation||'Correct answer: '+q.options[q.answer]}`;document.querySelectorAll('#options .option').forEach(b=>b.onclick=()=>answer(q,Number(b.dataset.i)));$('prevBtn').disabled=state.index===0;$('nextBtn').textContent=state.index===state.quiz.length-1?'Submit Practice':'Next →'}
function answer(q,i){if(state.answers[q.id]!==undefined)return;state.answers[q.id]=i;renderQuestion()}
async function finishQuiz(timedOut){clearInterval(state.timer);const score=state.quiz.reduce((n,q)=>n+(state.answers[q.id]===q.answer?1:0),0),answered=Object.keys(state.answers).length,duration=Math.round((Date.now()-state.startedAt)/1000);let server={score,total:state.quiz.length,percentage:Math.round(score*100/state.quiz.length),answered};try{server=await api('submit_attempt',{attemptId:state.attempt.attemptId,score,answered,durationSeconds:duration,timedOut})}catch(e){toast('Result saved locally; server sync failed.',true)}renderResult(server)}
function saveLocalFree(r){if(state.user?.status==='approved')return;const k='promo_free_perf_'+state.user.id;let rows=[];try{rows=JSON.parse(localStorage.getItem(k)||'[]')}catch{};rows.push({score:r.score,total:r.total,percentage:r.percentage,completed_at:new Date().toISOString()});localStorage.setItem(k,JSON.stringify(rows.slice(-100)))}
function localPerf(){const k='promo_free_perf_'+state.user.id;let rows=[];try{rows=JSON.parse(localStorage.getItem(k)||'[]')}catch{};const p=rows.map(x=>x.percentage),first=p[0]||0,latest=p.at(-1)||0;return {attempts:rows.map((x,i)=>({id:'local'+i,question_count:x.total,score:x.score,completed_at:x.completed_at,free_attempt:true,percentage:x.percentage})),summary:{attempts:rows.length,average:p.length?Math.round(p.reduce((a,c)=>a+c,0)/p.length):0,best:p.length?Math.max(...p):0,first,latest,improvement:latest-first}}}
function renderResult(r){saveLocalFree(r);setView('resultScreen');const premium=state.user.status==='approved';$('resultScreen').innerHTML=`<div class="result-card"><div class="result-ring"><strong>${r.percentage}%</strong><span>${r.score}/${r.total}</span></div><h2>${r.percentage>=80?'Excellent work!':r.percentage>=60?'Good progress!':'Keep practising!'}</h2><p>You answered ${r.answered??Object.keys(state.answers).length} questions.</p><button id="againBtn" class="primary block">Practise Again</button><button id="perfBtn2" class="ghost block">View Performance</button></div>${premium?'':subscriptionCard(state.user.status==='pending')}`;$('againBtn').onclick=renderDashboard;$('perfBtn2').onclick=showPerformance;$('subscribeBtn')?.addEventListener('click',requestSubscription);$('copyMomo')?.addEventListener('click',()=>navigator.clipboard?.writeText('0248481762'))}
async function showPerformance(){try{let d;if(state.user.status==='approved'){d=await api('performance')}else{d=localPerf()}setView('performanceScreen');const s=d.summary||{};$('performanceScreen').innerHTML=`<button id="backDash" class="ghost">← Dashboard</button><h2>My Performance</h2><div class="stats"><div><strong>${s.attempts||0}</strong><span>Attempts</span></div><div><strong>${s.average||0}%</strong><span>Average</span></div><div><strong>${s.best||0}%</strong><span>Best</span></div><div><strong>${(s.improvement||0)>=0?'+':''}${s.improvement||0}%</strong><span>Improvement</span></div></div><div class="history">${(d.attempts||[]).slice().reverse().map((a,i)=>`<div class="history-row"><b>${a.percentage}%</b><span>${a.score}/${a.question_count} • ${a.free_attempt?'Free':'Full'} practice</span><small>${new Date(a.completed_at).toLocaleDateString()}</small></div>`).join('')||'<p>No completed practice yet.</p>'}</div>`;$('backDash').onclick=renderDashboard}catch(e){toast(e.message,true)}}
async function logout(){try{await api('logout')}catch{}localStorage.removeItem('promo_token_v3');state.token='';state.user=null;state.bank=window.FREE_BANK||[];showAuth('chooser')}
document.addEventListener('DOMContentLoaded',boot);
})();
