(()=>{
'use strict';
const API='https://dhnrrruishllmnhafjdd.supabase.co/functions/v1/ges-quiz-api';
const $=id=>document.getElementById(id);
const state={token:localStorage.getItem('promo_token_v3')||'',deviceId:'',user:null,settings:{},bank:window.FREE_BANK||[],attempt:null,quiz:[],answers:{},index:0,startedAt:0,timer:null,left:0};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function randomDeviceId(){const a=new Uint8Array(32);crypto.getRandomValues(a);return 'dev_'+Array.from(a,b=>b.toString(16).padStart(2,'0')).join('')}
function cookieDevice(){const m=document.cookie.match(/(?:^|;\s*)promo_device_v3=([^;]+)/);return m?decodeURIComponent(m[1]):''}
function setCookieDevice(id){document.cookie=`promo_device_v3=${encodeURIComponent(id)}; Max-Age=157680000; Path=/; SameSite=Lax; Secure`}
function idbRead(){return new Promise(resolve=>{try{const r=indexedDB.open('promo_secure_store',1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('kv'))r.result.createObjectStore('kv')};r.onerror=()=>resolve('');r.onsuccess=()=>{const tx=r.result.transaction('kv','readonly'),g=tx.objectStore('kv').get('deviceId');g.onsuccess=()=>resolve(g.result||'');g.onerror=()=>resolve('')}}catch{resolve('')}})}
function idbWrite(id){return new Promise(resolve=>{try{const r=indexedDB.open('promo_secure_store',1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('kv'))r.result.createObjectStore('kv')};r.onerror=()=>resolve();r.onsuccess=()=>{const tx=r.result.transaction('kv','readwrite');tx.objectStore('kv').put(id,'deviceId');tx.oncomplete=()=>resolve();tx.onerror=()=>resolve()}}catch{resolve()}})}
async function ensureDeviceId(){let id='';try{id=localStorage.getItem('promo_device_v3')||''}catch{}if(!id)id=cookieDevice();if(!id)id=await idbRead();if(!id)id=randomDeviceId();try{localStorage.setItem('promo_device_v3',id)}catch{}setCookieDevice(id);await idbWrite(id);try{navigator.storage?.persist?.()}catch{}return id}
async function api(action,body={}){const c=new AbortController();const t=setTimeout(()=>c.abort(),15000);try{const payload={action,...body};if(['register','login'].includes(action))payload.deviceId=state.deviceId;const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json',...(state.token?{Authorization:'Bearer '+state.token}:{})},body:JSON.stringify(payload),signal:c.signal});const d=await r.json().catch(()=>({error:'Invalid server response'}));if(!r.ok)throw Object.assign(new Error(d.error||'Request failed'),{data:d,status:r.status});return d}finally{clearTimeout(t)}}
function toast(msg,bad=false){const x=$('toastRoot');x.innerHTML=`<div class="toast ${bad?'bad':''}">${esc(msg)}</div>`;setTimeout(()=>x.innerHTML='',3200)}
function setView(id){['authScreen','dashboardScreen','quizScreen','resultScreen','performanceScreen'].forEach(x=>$(x)?.classList.add('hidden'));$(id)?.classList.remove('hidden');scrollTo(0,0)}
function showAuth(mode='chooser'){setView('authScreen');$('authChooser').classList.toggle('hidden',mode!=='chooser');$('registerPanel').classList.toggle('hidden',mode!=='register');$('loginPanel').classList.toggle('hidden',mode!=='login');$('authTitle').textContent=mode==='register'?'Create your account':mode==='login'?'Welcome back':'Start your practice';$('authSubtitle').textContent=mode==='register'?'New users register once on this device, then use the one-time free practice.':mode==='login'?'Enter the telephone number and 4-digit password you used when registering.':'New users register once. Existing users should log in.'}
async function boot(){state.deviceId=await ensureDeviceId();bind();if(state.token){try{const d=await api('me');state.user=d.user;state.settings=d.settings||{};await prepareBank();renderDashboard();return}catch(e){localStorage.removeItem('promo_token_v3');state.token=''}}showAuth('chooser')}
function bind(){$('newUserCard').onclick=()=>showAuth('register');$('existingUserCard').onclick=()=>showAuth('login');document.querySelectorAll('[data-back-auth]').forEach(b=>b.onclick=()=>showAuth('chooser'));$('registerForm').onsubmit=async e=>{e.preventDefault();const b=$('registerBtn');b.disabled=true;b.textContent='Creating secure account…';try{const d=await api('register',{fullName:$('regName').value,phone:$('regPhone').value,pin:$('regPin').value});saveSession(d);toast('Registration successful. Your one-time free trial is ready.');renderDashboard()}catch(err){toast(err.message,true)}finally{b.disabled=false;b.textContent='Register & Start Free Practice'}};$('loginForm').onsubmit=async e=>{e.preventDefault();const b=$('loginBtn');b.disabled=true;b.textContent='Logging in securely…';try{const d=await api('login',{phone:$('loginPhone').value,pin:$('loginPin').value});saveSession(d);await prepareBank();toast(d.user?.status==='approved'?'Login successful — full access active':'Login successful');renderDashboard()}catch(err){toast(err.message,true)}finally{b.disabled=false;b.textContent='Log In & Open Quiz'}};$('prevBtn').onclick=()=>{if(state.index>0){state.index--;renderQuestion()}};$('nextBtn').onclick=()=>{if(state.index<state.quiz.length-1){state.index++;renderQuestion()}else finishQuiz(false)};$('exitQuiz').onclick=()=>{if(confirm('Leave this practice? Your current progress will not be submitted.')){clearInterval(state.timer);renderDashboard()}}}
function saveSession(d){state.token=d.token;state.user=d.user;state.settings=d.settings||{};localStorage.setItem('promo_token_v3',state.token)}
function b64Bytes(s){return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
async function prepareBank(){state.bank=window.FREE_BANK||[];if(state.user?.status!=='approved')return;if(!window.PREMIUM_BANK_DATA||!window.PREMIUM_BANK_IV){toast('Encrypted full bank is still loading. Reload the page.',true);return}try{const k=await api('get_full_key');const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(k.key));const key=await crypto.subtle.importKey('raw',digest,{name:'AES-GCM'},false,['decrypt']);const compressed=await crypto.subtle.decrypt({name:'AES-GCM',iv:b64Bytes(window.PREMIUM_BANK_IV)},key,b64Bytes(window.PREMIUM_BANK_DATA));const stream=new Blob([compressed]).stream().pipeThrough(new DecompressionStream('gzip'));const bank=JSON.parse(await new Response(stream).text());if(!Array.isArray(bank)||bank.length!==922)throw new Error('Bank verification failed');state.bank=bank}catch(e){console.error(e);state.bank=window.FREE_BANK||[];toast('Secure full bank could not be unlocked. Please log in again.',true)}}
function isLocked(){return state.user?.status!=='approved'&&(!!state.user?.freeAttemptCompleted||state.user?.status==='pending')}
function renderDashboard(){setView('dashboardScreen');const u=state.user||{},premium=u.status==='approved',pending=u.status==='pending',locked=isLocked();const topics=[...new Set(state.bank.map(q=>q.topic))].sort(),ranks=[...new Set(state.bank.map(q=>q.rank))].sort();const statusText=premium?'✓ FULL ACCESS':locked?'🔒 TRIAL USED — ADMIN ACTIVATION REQUIRED':'ONE-TIME FREE TRIAL';$('dashboardScreen').innerHTML=`<div class="dash-head"><div><small>WELCOME</small><h2>${esc(u.fullName||u.full_name||'Learner')}</h2><p>${premium?'All 922 questions unlocked':locked?'Your free trial is finished. Further practice is locked.':'You have one free 30-question trial.'}</p></div><button id="logoutBtn" class="ghost">Log out</button></div><div class="status-pill ${premium?'ok':locked?'pending':'free'}">${statusText}</div><div class="practice-card"><div class="card-icon">${locked?'🔒':'📝'}</div><div><h3>${premium?'Choose your practice':locked?'Practice Locked':'Free 30-question trial'}</h3><p>${premium?'Select the number of questions and optional filters.':locked?'The first 30-question trial has been completed. Only the administrator can activate further practice.':'You may complete these 30 free questions once. After submission, the account locks until admin activation.'}</p></div>${premium?`<div class="grid2"><label>Questions<select id="countSel"><option>20</option><option selected>30</option><option>50</option><option>100</option><option>200</option><option>500</option><option>922</option></select></label><label>Rank<select id="rankSel"><option>All</option>${ranks.map(x=>`<option>${esc(x)}</option>`).join('')}</select></label></div><label>Topic<select id="topicSel"><option>All</option>${topics.map(x=>`<option>${esc(x)}</option>`).join('')}</select></label>`:''}${locked?'':`<button id="startPractice" class="primary block pulse-soft">▶ ${premium?'Start Practice':'Start My One-Time Free Trial'}</button>`}</div><div class="dash-actions"><button id="performanceBtn" class="action-card"><span>📈</span><b>My Performance</b><small>View completed scores</small></button></div>${locked&&!premium?subscriptionCard(pending):''}<div class="independent-note">Independent study and revision platform. Not an official GES examination portal.</div>`;$('logoutBtn').onclick=logout;$('startPractice')?.addEventListener('click',startPractice);$('performanceBtn').onclick=showPerformance;$('subscribeBtn')?.addEventListener('click',requestSubscription);$('copyMomo')?.addEventListener('click',()=>navigator.clipboard?.writeText('0248481762').then(()=>toast('MoMo number copied')))}
function subscriptionCard(pending){return `<section class="subscribe-card blink-border"><div class="spark">✨</div><div class="sub-badge">🔒 ACCOUNT LOCKED — ACTIVATE FULL ACCESS</div><h3>Your free trial is complete</h3><p>Further quiz practice is disabled until the administrator activates your account. Full access unlocks all 922 encrypted questions, flexible practice sizes, filters and performance tools.</p><div class="price">GH₵30</div><div class="momo"><small>MTN MOBILE MONEY</small><strong>0248 481 762</strong><b>ISAAC BOAHEN</b><button id="copyMomo" class="ghost">Copy number</button></div><a class="whatsapp" target="_blank" rel="noopener" href="https://wa.me/233248481762?text=${encodeURIComponent('Hello Sir Isaac, I have completed my one-time free 30-question trial. My account is now locked and I want full access. I have paid/will pay GH₵30 to 0248 481 762 (ISAAC BOAHEN). Please activate my account.')} ">🟢 WhatsApp Sir Isaac for Activation</a><button id="subscribeBtn" class="primary block">${pending?'Activation Request Sent':'I Have Paid / Request Admin Activation'}</button>${pending?'<small class="pending-text">Your account is locked and waiting for administrator approval.</small>':''}</section>`}
async function requestSubscription(){if(state.user?.status==='approved')return;try{const d=await api('request_subscription');state.user.status=d.status||'pending';state.user.freeAttemptCompleted=true;toast('Activation request sent to admin');renderDashboard()}catch(e){toast(e.message,true)}}
async function startPractice(){const premium=state.user.status==='approved';if(!premium&&isLocked())return toast('Your free trial is finished. Admin activation is required.',true);let count=premium?Number($('countSel').value):30,rank=premium?$('rankSel').value:'All',topic=premium?$('topicSel').value:'All';let pool=state.bank.filter(q=>(rank==='All'||q.rank===rank)&&(topic==='All'||q.topic===topic));if(!pool.length)return toast('No questions match those filters.',true);count=Math.min(count,pool.length);pool=[...pool].sort(()=>Math.random()-.5);state.quiz=pool.slice(0,count);state.answers={};state.index=0;state.startedAt=Date.now();try{state.attempt=await api('start_attempt',{count,rank,topic})}catch(e){if(e.data?.locked){state.user.freeAttemptCompleted=true;state.user.status='pending';renderDashboard()}return toast(e.message,true)}state.left=count*60;setView('quizScreen');startTimer();renderQuestion()}
function startTimer(){clearInterval(state.timer);tick();state.timer=setInterval(()=>{state.left--;tick();if(state.left<=0){clearInterval(state.timer);finishQuiz(true)}},1000)}
function tick(){const m=Math.floor(state.left/60),s=state.left%60;$('timerText').textContent=`${m}:${String(s).padStart(2,'0')}`}
function renderQuestion(){const q=state.quiz[state.index],picked=state.answers[q.id];$('qProgress').textContent=`Question ${state.index+1} of ${state.quiz.length}`;$('answeredCount').textContent=`${Object.keys(state.answers).length} answered`;$('progressBar').style.width=`${((state.index+1)/state.quiz.length)*100}%`;$('qTags').innerHTML=`<span class="tag">${esc(q.rank)}</span><span class="tag">${esc(q.topic)}</span>`;$('qNo').textContent=`QUESTION ${state.index+1}`;$('qText').innerHTML=q.q;$('options').innerHTML=q.options.map((o,i)=>`<button class="option ${picked!==undefined?(i===q.answer?'correct':i===picked?'wrong':''):''}" data-i="${i}" ${picked!==undefined?'disabled':''}><span class="letter">${String.fromCharCode(65+i)}</span><span class="otxt">${o}</span><span class="mark">${picked!==undefined?(i===q.answer?'✓':i===picked?'✕':''):''}</span></button>`).join('');$('explanation').classList.toggle('hidden',picked===undefined);$('explanation').innerHTML=picked===undefined?'':`<strong>Explanation:</strong> ${q.explanation||'Correct answer: '+q.options[q.answer]}`;document.querySelectorAll('#options .option').forEach(b=>b.onclick=()=>answer(q,Number(b.dataset.i)));$('prevBtn').disabled=state.index===0;$('nextBtn').textContent=state.index===state.quiz.length-1?'Submit Practice':'Next →'}
function answer(q,i){if(state.answers[q.id]!==undefined)return;state.answers[q.id]=i;renderQuestion()}
async function finishQuiz(timedOut){clearInterval(state.timer);const score=state.quiz.reduce((n,q)=>n+(state.answers[q.id]===q.answer?1:0),0),answered=Object.keys(state.answers).length,duration=Math.round((Date.now()-state.startedAt)/1000);let server={score,total:state.quiz.length,percentage:Math.round(score*100/state.quiz.length),answered};const wasFree=state.user.status!=='approved';try{server=await api('submit_attempt',{attemptId:state.attempt.attemptId,score,answered,durationSeconds:duration,timedOut});if(server.userStatus)state.user.status=server.userStatus;if(server.freeAttemptCompleted!==undefined)state.user.freeAttemptCompleted=server.freeAttemptCompleted}catch(e){toast('Could not confirm result with server. Reconnect before continuing.',true)}if(wasFree){state.user.freeAttemptCompleted=true;if(state.user.status!=='approved')state.user.status='pending'}renderResult(server,wasFree)}
function renderResult(r,wasFree=false){setView('resultScreen');const premium=state.user.status==='approved';const locked=wasFree&&!premium;$('resultScreen').innerHTML=`<div class="result-card"><div class="result-ring"><strong>${r.percentage}%</strong><span>${r.score}/${r.total}</span></div><h2>${locked?'🔒 Trial Completed — Account Locked':r.percentage>=80?'Excellent work!':r.percentage>=60?'Good progress!':'Keep practising!'}</h2><p>${locked?'You have used your one free 30-question trial. Further practice is disabled until the administrator activates your account.':`You answered ${r.answered??Object.keys(state.answers).length} questions.`}</p><button id="dashBtn" class="ghost block">Back to Dashboard</button><button id="perfBtn2" class="ghost block">View Performance</button></div>${locked?subscriptionCard(true):''}`;$('dashBtn').onclick=renderDashboard;$('perfBtn2').onclick=showPerformance;$('subscribeBtn')?.addEventListener('click',requestSubscription);$('copyMomo')?.addEventListener('click',()=>navigator.clipboard?.writeText('0248481762'))}
async function showPerformance(){try{const d=await api('performance');setView('performanceScreen');const s=d.summary||{};$('performanceScreen').innerHTML=`<button id="backDash" class="ghost">← Dashboard</button><h2>My Performance</h2><div class="stats"><div><strong>${s.attempts||0}</strong><span>Attempts</span></div><div><strong>${s.average||0}%</strong><span>Average</span></div><div><strong>${s.best||0}%</strong><span>Best</span></div><div><strong>${(s.improvement||0)>=0?'+':''}${s.improvement||0}%</strong><span>Improvement</span></div></div><div class="history">${(d.attempts||[]).slice().reverse().map(a=>`<div class="history-row"><b>${a.percentage}%</b><span>${a.score}/${a.question_count} • ${a.free_attempt?'Free trial':'Full'} practice</span><small>${new Date(a.completed_at).toLocaleDateString()}</small></div>`).join('')||'<p>No completed practice yet.</p>'}</div>${isLocked()?subscriptionCard(state.user.status==='pending'):''}`;$('backDash').onclick=renderDashboard;$('subscribeBtn')?.addEventListener('click',requestSubscription);$('copyMomo')?.addEventListener('click',()=>navigator.clipboard?.writeText('0248481762'))}catch(e){toast(e.message,true)}}
async function logout(){try{await api('logout')}catch{}localStorage.removeItem('promo_token_v3');state.token='';state.user=null;state.bank=window.FREE_BANK||[];showAuth('chooser')}
document.addEventListener('DOMContentLoaded',boot);
})();
